
spring.datasource.url=jdbc:postgresql://localhost:5432/kintaidb
spring.datasource.username=postgres
spring.datasource.password=Taiyo3sun
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql


spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

server.port=8080

logging.level.org.springframework.security=DEBUG
logging.level.com.example.kintai=DEBUG
